version: "3.8"

services:
  fast_service:
    build:
      context: ./fast_service
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
