version: "3.8"

services:
  fast_service:
    build:
      context: ./fast_service
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./fast_service:/app
    environment:
      - PYTHONUNBUFFERED=1

  node_service:
    build:
      context: ./node_service
      dockerfile: Dockerfile
    container_name: node_service
    ports:
      - "3000:3000"
    volumes:
      - ./node_service:/app
    command: ["node", "dist/main"]
