version: "3.8"

services:
  fast_service:
    build:
      context: ./fast_service
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./fast_service:/app
    environment:
      - PYTHONUNBUFFERED=1

  node_service:
    build:
      context: ./node_service
    container_name: nest_service
    ports:
      - "3000:3000"
    volumes:
      - ./node_service:/app           # Монтируем текущий код
      - /app/node_modules              # Защищаем node_modules
    command: npm run start:dev main    # Автоперезагрузка
    environment:
      - CHOKIDAR_USEPOLLING=true      # Важно для отслеживания изменений
      - WATCHPACK_POLLING=true         # Дополнительный флаг для вебпака